version: '3.7'
services:
  users-db:
    container_name: 'users-db-container'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: root
      MYSQL_DATABASE: mysql
    ports:
      - 3306:3306
  users-service:
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: root
    container_name: 'users-service-container'
    depends_on:
      - users-db
    build: 
      context: .
    ports:
      - 8080:8080